"""Stage 4: generate per-query C++ and loop until it compiles and matches gold.

The heavy stage, and the one where the reward signal is real: the compiler and
the gold results decide whether a query is done, not the model's own assessment.

Two budgets, not one. ``compile.max_fix_rounds`` bounds compile and link
failures; ``params.max_correctness_rounds`` bounds result mismatches. They are
separate because the failures are different sizes — a missing include is a
one-line fix, while a wrong answer usually means the plan was wrong and the
implementation has to change shape — and a single shared budget would let a
string of trivial compile errors consume the rounds a mismatch needs.

What this stage will not do is claim correctness it did not check. With no run
command configured, or with gold unavailable, each query is reported as
``unverified`` and the run summary carries ``verified=False``; the ``optimize``
stage then refuses to start rather than optimizing code of unknown correctness.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

from agent.config.models import LevelConfig
from agent.rlm.compile import CompileResult, arrow_pkgconfig_flags
from agent.stages.base import Artifact, Stage, StageResult
from agent.stages.divide import DESCRIPTIONS_KEY, LEVELS_KEY
from agent.stages.execution import QueryRunner
from agent.stages.fixing import compile_verdict, fix_loop, no_progress_reason, repair_signature
from agent.stages.gold import GoldProvider, GoldSet
from agent.stages.parsing import Query, extract_code, parse_workload
from agent.stages.predict import invoke
from agent.stages.results import Comparison, compare_tables, load_table, parse_table
from agent.trace.span import new_span, stage_context

FIX_PROMPT_ID = "fix_compile_errors"
LOADER_PROMPT_ID = "query_codegen_loader_task"
MAIN_PROMPT_ID = "query_codegen_main_task"

# Where the LLM-generated build entry points live, relative to the workspace
# root. CMakeLists.txt (generated by _sync_cmake_project) references these
# same paths, so they must stay in sync with each other.
LOADER_REL_PATH = "src/loader.cpp"
MAIN_REL_PATH = "src/main.cpp"
DISPATCH_HEADER_REL_PATH = "query_dispatch.hpp"

# Terminal states a query can end in. Every query gets exactly one, and they are
# all recorded: a query that is quietly absent from the report reads as "fine".
STATUS_MATCHED = "matched"
STATUS_MISMATCH = "mismatch"
STATUS_COMPILE_FAILED = "compile_failed"
STATUS_BUILD_FAILED = "build_failed"
STATUS_RUN_FAILED = "run_failed"
STATUS_NO_GOLD = "no_gold"
STATUS_UNVERIFIED = "unverified"


def _signature_class() -> Any:
    """Build the generation signature."""
    import dspy

    class GenerateQueryImplementation(dspy.Signature):
        """Implement one SQL query as C++ over an in-memory storage layout.

        The storage layout is fixed and shared by every query: read it, never
        change it, and never add a structure that exists only to serve this one
        query. Compile the query's plan into the code — no SQL parsing at
        runtime.

        Output the complete translation unit and nothing else.
        """

        task: str = dspy.InputField(desc="The interface, output format and constraints to obey.")
        query_id: str = dspy.InputField(desc="Identifier for this query.")
        query_sql: str = dspy.InputField(desc="The SQL statement to implement.")
        query_intent: str = dspy.InputField(
            desc="The query's header comment, if the workload file had one. May be empty."
        )
        namespace: str = dspy.InputField(desc="Namespace the storage layout is declared in.")
        storage_header: str = dspy.InputField(desc="The generated storage-layout header, in full.")
        header_include: str = dspy.InputField(desc="The #include line for that header.")
        level_text: str = dspy.InputField(desc="The hint level's description of schema and layout.")
        cpp_standard: str = dspy.InputField(desc="C++ standard the source must compile under.")
        source_code: str = dspy.OutputField(desc="The complete C++ source. No markdown fences.")
        notes: str = dspy.OutputField(desc="The plan you implemented, in two or three sentences.")

    return GenerateQueryImplementation


def _loader_signature_class() -> Any:
    """Build the loader-generation signature."""
    import dspy

    class GenerateLoader(dspy.Signature):
        """Implement the storage layout's ingestion entry point in C++.

        The header already declares the entry point and documents, column by
        column, exactly how each field must be encoded. Follow those comments
        exactly - they are the encoding specification, not the raw dataset's
        own column shapes.

        Output the complete translation unit and nothing else.
        """

        task: str = dspy.InputField(desc="The interface, data source and constraints to obey.")
        storage_header: str = dspy.InputField(desc="The generated storage-layout header, in full.")
        header_include: str = dspy.InputField(desc="The #include line for that header.")
        entry_signature: str = dspy.InputField(desc="The exact ingestion entry point to define.")
        dataset_description: str = dspy.InputField(
            desc="Where the dataset lives and which Parquet file backs each table."
        )
        cpp_standard: str = dspy.InputField(desc="C++ standard the source must compile under.")
        loader_code: str = dspy.OutputField(desc="The complete C++ source. No markdown fences.")
        notes: str = dspy.OutputField(desc="The approach you implemented, in two or three sentences.")

    return GenerateLoader


def _main_signature_class() -> Any:
    """Build the main.cpp-generation signature."""
    import dspy

    class GenerateMain(dspy.Signature):
        """Implement the engine's command-line entry point in C++.

        Wiring only: parse argv, build the database exactly once, dispatch to
        the requested query, write its output. No query logic and no data
        ingestion belong in this file.

        Output the complete translation unit and nothing else.
        """

        task: str = dspy.InputField(desc="The interface and constraints to obey.")
        storage_header_include: str = dspy.InputField(
            desc="The #include line for the storage-layout header."
        )
        dispatch_header: str = dspy.InputField(
            desc="The dispatch header this file must include and use, in full."
        )
        entry_signature: str = dspy.InputField(desc="The loader's entry point to call, exactly once.")
        run_command: str = dspy.InputField(
            desc="The exact command line this program must parse and satisfy."
        )
        cpp_standard: str = dspy.InputField(desc="C++ standard the source must compile under.")
        main_code: str = dspy.OutputField(desc="The complete C++ source. No markdown fences.")
        notes: str = dspy.OutputField(desc="The approach you implemented, in two or three sentences.")

    return GenerateMain


class QueryCodegenStage(Stage):
    """Generate a C++ implementation per query, then fix it until it is correct.

    Supports one or more hint levels sequentially. Each level generates separate
    code into separate output directories. To generate multiple levels from a
    single config, list them all in ``stages.query_codegen.active_levels``; the
    stage will iterate through each one automatically.

    Requires: ``schema_levels``, ``storage_layout_headers``.
    Produces: ``query_sources``, ``correctness_report``.

    Config:
        ``common.inputs.queries`` - the workload, split into queries whose
            ``-- Q<n>`` headers become the ids used throughout the report.
        ``stages.query_codegen.active_levels`` - one or more levels. When
            multiple levels are specified, they are generated sequentially,
            each into a separate subdirectory under ``gen_project_root``.
            For backward compatibility, a single level works as before.
        ``common.gold`` - where reference results come from. See
            :class:`agent.stages.gold.GoldProvider`.
        ``compile.max_fix_rounds`` - compile and link repair budget per query.
        ``stages.query_codegen.params``:
            ``run_command`` - how to execute one query. Placeholders:
                ``{query_id}``, ``{query_text}``, ``{output}``,
                ``{project_root}``, ``{build_dir}``, ``{dataset_dir}``,
                ``{sf}``, ``{trace}``. Without it, nothing is verified.
            ``max_correctness_rounds`` - mismatch repair budget (default 3).
            ``float_tolerance`` - absolute tolerance for numeric cells (1e-6).
            ``header_mode`` - which side has a header row that is not data:
                ``"gold"`` (default, since DuckDB writes gold with a header and
                the prompt tells the engine to print bare rows), ``"none"``,
                ``"actual"`` or ``"both"``.
            ``sort_rows`` - compare as multisets. Only for a workload with no
                ``ORDER BY``; it hides ordering bugs otherwise.
            ``source_dir`` - where sources are written (default ``src/queries``).
            ``entry_signature`` - overrides the generated query entry point.
            ``build_project`` - ``"auto"`` (default), true or false.
            ``rlm_tools`` - hand the model the workspace tools as well.
            ``ingestion_signature`` - overrides the loader's entry point
                signature. Must match ``hppgen``'s (see
                ``HppGenStage._ingestion_signature``) if either is set;
                both default to ``build_database`` via
                ``database_type_name``/``ingestion_function_name``.
            ``loader_task``, ``main_task`` - inline overrides for the
                ``query_codegen_loader_task``/``query_codegen_main_task``
                prompts.

        Single-active-level runs only (multi-level runs skip this
        entirely, see the comment at the ``_generate_build_entrypoint`` call
        site) also get an LLM-generated loader (``src/loader.cpp``, reads
        ``common.gold.dataset_dir``'s Parquet files via Arrow/Parquet C++ into
        the storage layout) and ``src/main.cpp`` (parses ``run_command``,
        calls the loader once, dispatches to a query). Both are generated once
        per level, before any query, verified by compiling and cached like a
        header. Skipped entirely (falls back to each query compiling and
        running standalone via ``run_command``) when
        ``common.gold.dataset_dir`` is not configured.

    Output artifacts:
        ``query_sources`` - list of artifacts, one per level:
            ``{"level":..., "sources": {"<query id>": path}}``.
        ``correctness_report`` - per query per level: status, round counts,
            the first mismatch, and the gold file it was compared against.
    """

    name = "query_codegen"
    requires = ("schema_levels", "storage_layout_headers")
    produces = ("query_sources", "correctness_report")
    description = "Generate C++ per query and fix until it compiles and matches gold results."
    default_prompt_ids = ("query_codegen_task", FIX_PROMPT_ID, LOADER_PROMPT_ID, MAIN_PROMPT_ID)

    def run(self, inputs: Mapping[str, Artifact]) -> StageResult:
        started = time.perf_counter()
        cfg = self.cfg

        try:
            levels = self._get_levels()
            if not levels:
                raise ValueError("No active levels configured for query_codegen")
            workspace = self.ctx.workspace_for(cfg)
        except Exception as exc:
            return self._fail(str(exc), started)

        queries_path = cfg.input_path("queries", required=True)
        queries = parse_workload(
            Path(str(queries_path)).read_text(encoding="utf-8", errors="replace")
        )
        if not queries:
            return self._fail(f"No SQL statements found in {queries_path}.", started)

        split = inputs["schema_levels"].read_json()
        headers = inputs["storage_layout_headers"].read_json().get("headers") or {}
        gold = self._gold(queries)
        runner = self._runner()

        # Collect all level results
        all_level_results = []

        with stage_context(self.name):
            for level in levels:
                level_text = str((split.get(LEVELS_KEY) or {}).get(level.name, ""))
                description = str((split.get(DESCRIPTIONS_KEY) or {}).get(level.name, ""))
                if not level_text.strip():
                    return self._fail(
                        f"The schema_levels artifact has no text for level '{level.name}'.",
                        started,
                    )

                header_path = headers.get(level.name)
                if not header_path or not Path(header_path).exists():
                    return self._fail(
                        f"No generated header for level '{level.name}' at {header_path!r}. "
                        f"Run hppgen for this level first.",
                        started,
                    )
                header_text = Path(header_path).read_text(encoding="utf-8", errors="replace")

                # The auto-generated CMake build assumes one set of query
                # sources for the whole project; it isn't level-aware, so with
                # several active levels it is skipped in favor of each query
                # compiling on its own via run_command. Single level runs get
                # an LLM-generated loader + main.cpp (once per level, before
                # any query), verified the same way a header is: compile,
                # repair, only cache what verified. Not critical if it fails
                # or is skipped (no dataset_dir configured) - queries still
                # compile individually via their own run_command.
                if len(levels) == 1:
                    self._generate_build_entrypoint(workspace, level, Path(header_path), header_text)

                task = self.registry.render_any(
                    self.prompt_ids()[0] if self.prompt_ids() else None,
                    inline=cfg.params.get("task"),
                    entry_signature=self._entry_signature(level),
                    delimiter=self._param("delimiter", ","),
                    header_rule=self._header_rule(),
                )

                sources: dict[str, str] = {}
                report: dict[str, Any] = {}

                with new_span("level", level.name, writer=self.writer):
                    for query in queries:
                        with new_span("query", query.id, writer=self.writer):
                            row = self._process_query(
                                query=query,
                                level=level,
                                level_text=level_text,
                                description=description,
                                header_path=Path(header_path),
                                header_text=header_text,
                                task_text=task.text,
                                task_fingerprint=task.fingerprint,
                                gold=gold,
                                runner=runner,
                                workspace=workspace,
                            )
                        report[query.id] = row
                        if row.get("source"):
                            sources[query.id] = row["source"]

                counts = _tally(report)
                verified = counts.get(STATUS_MATCHED, 0) == len(queries)
                unverified = counts.get(STATUS_UNVERIFIED, 0) + counts.get(STATUS_NO_GOLD, 0)

                broken = [
                    qid
                    for qid, row in report.items()
                    if row["status"] in (STATUS_COMPILE_FAILED, STATUS_BUILD_FAILED, STATUS_RUN_FAILED)
                ]
                mismatched = [qid for qid, row in report.items() if row["status"] == STATUS_MISMATCH]

                meta: dict[str, Any] = {
                    "model": cfg.model.name,
                    "prompt_ids": list(task.prompt_ids),
                    "level": level.name,
                    "run_id": self.ctx.run_id,
                }
                if not broken and not mismatched:
                    # Only a trustworthy artifact carries the fingerprint that marks it
                    # current; otherwise the next run would skip the retry.
                    meta["input_fingerprint"] = self.input_fingerprint(inputs)

                sources_artifact = self.store.put_json(
                    self.name,
                    "query_sources",
                    {"level": level.name, "namespace": level.namespace, "sources": sources},
                    meta=meta,
                    target=cfg.outputs.get("query_sources"),
                )
                report_artifact = self.store.put_json(
                    self.name,
                    "correctness_report",
                    {
                        "level": level.name,
                        "verified": verified,
                        "run_command": runner.template,
                        "gold": {"mode": gold.mode, "summary": gold.summary()},
                        "counts": counts,
                        "queries": report,
                    },
                    meta=meta,
                    target=cfg.outputs.get("correctness_report"),
                )

                all_level_results.append(
                    {
                        "level": level.name,
                        "sources_artifact": sources_artifact,
                        "report_artifact": report_artifact,
                        "counts": counts,
                        "verified": verified,
                        "unverified": unverified,
                        "broken": broken,
                        "mismatched": mismatched,
                        "num_queries": len(queries),
                    }
                )

        # Aggregate results from all levels. For the common single-level case
        # these collapse to exactly that level's own numbers, so the metrics
        # shape stays backward compatible with a single-level run.
        all_broken: list[str] = []
        all_mismatched: list[str] = []
        combined_counts: dict[str, int] = {}
        for r in all_level_results:
            all_broken.extend(r["broken"])
            all_mismatched.extend(r["mismatched"])
            for status, count in r["counts"].items():
                combined_counts[status] = combined_counts.get(status, 0) + count

        verified = all(r["verified"] for r in all_level_results)
        unverified = sum(r["unverified"] for r in all_level_results)

        metrics: dict[str, Any] = {
            "queries": len(queries),
            "verified": verified,
            "unverified": unverified,
            **{f"n[{status}]": count for status, count in sorted(combined_counts.items())},
        }
        if len(all_level_results) > 1:
            metrics["levels"] = len(all_level_results)
            metrics["levels_verified"] = sum(r["verified"] for r in all_level_results)

        # Use the last level's artifacts as the primary ones
        if all_level_results:
            last = all_level_results[-1]
            artifacts = {
                "query_sources": last["sources_artifact"],
                "correctness_report": last["report_artifact"],
            }
        else:
            artifacts = {}

        if all_broken or all_mismatched:
            problems = []
            if all_broken:
                problems.append(
                    f"{len(all_broken)} did not build ({', '.join(set(all_broken[:5]))})"
                )
            if all_mismatched:
                problems.append(
                    f"{len(all_mismatched)} did not match gold ({', '.join(set(all_mismatched[:5]))})"
                )
            return self.make_result(
                artifacts=artifacts,
                metrics=metrics,
                status="failed",
                error="; ".join(problems) + ". See the correctness_report artifact.",
                duration_s=time.perf_counter() - started,
            )

        return self.make_result(
            artifacts=artifacts, metrics=metrics, duration_s=time.perf_counter() - started
        )

    # --- per query --------------------------------------------------------

    def _process_query(
        self,
        query: Query,
        level: LevelConfig,
        level_text: str,
        description: str,
        header_path: Path,
        header_text: str,
        task_text: str,
        task_fingerprint: str,
        gold: GoldSet,
        runner: QueryRunner,
        workspace: Any,
    ) -> dict[str, Any]:
        """Generate, compile, build, run and compare one query.

        The loop is written out rather than delegated to
        :func:`agent.stages.fixing.fix_loop` because the two budgets have to be
        spent independently, which a single-verifier loop cannot express.
        """
        cfg = self.cfg
        rel_source = self._source_path(query, level)
        row: dict[str, Any] = {
            "query_id": query.id,
            "sql": query.text,
            "status": STATUS_UNVERIFIED,
            "source": "",
            "compiled": False,
            "built": False,
            "ran": False,
            "matched": False,
            "compile_rounds": 0,
            "correctness_rounds": 0,
            "report": "",
            "gold": str(gold.files[query.id].path) if query.id in gold.files else "",
            "cache_hit": False,
            "predictor": "",
            "notes": "",
        }

        payload = {
            "task": task_text,
            "query_id": query.id,
            "query_sql": query.text,
            "query_intent": query.label,
            "namespace": level.namespace,
            "storage_header": header_text,
            "header_include": self._include_line(header_path, workspace),
            "level_text": f"{description}\n\n{level_text}".strip(),
            "cpp_standard": cfg.compile.cpp_standard,
        }
        key = self.cache.make_key(
            {
                **payload,
                "level": level.name,
                "source": rel_source,
                "tolerance": self._float_tolerance(),
                "header_mode": self._header_mode(),
            },
            prompt_fingerprint=task_fingerprint,
            model_signature=cfg.model.signature(),
            kind="stage",
        )

        cached = self.cache.get(key)
        if cached is not None and isinstance(cached.value, dict):
            content = str(cached.value.get("source", ""))
            row["cache_hit"] = True
            row["predictor"] = str(cached.value.get("predictor", ""))
            row["notes"] = str(cached.value.get("notes", ""))
        else:
            first = self._call_model(payload)
            content = extract_code(first["source_code"])
            row["predictor"] = first["predictor"]
            row["notes"] = first["notes"]

        gold_file = gold.files.get(query.id)
        max_compile = cfg.compile.max_fix_rounds
        max_correctness = self._max_correctness_rounds()

        while True:
            workspace.write_file(rel_source, content)
            row["source"] = str(workspace.safe_path(rel_source))

            compiled = workspace.compile_file(rel_source, syntax_only=True)
            if not compiled.ok and not compiled.compiler_missing:
                if row["compile_rounds"] >= max_compile:
                    row["status"] = STATUS_COMPILE_FAILED
                    row["report"] = compiled.brief()
                    return row
                candidate = self._call_repair(content, compiled.brief(), compiled)
                stop = no_progress_reason(content, candidate)
                if stop:
                    row["status"] = STATUS_COMPILE_FAILED
                    row["report"] = f"{compiled.brief()}\n(stopped: {stop})"
                    return row
                content, row["compile_rounds"] = candidate, row["compile_rounds"] + 1
                continue
            row["compiled"] = True

            if self._should_build(workspace):
                self._sync_cmake_project(workspace, level)
                build = workspace.build_project()
                if not build.ok and not build.compiler_missing:
                    if row["compile_rounds"] >= max_compile:
                        row["status"] = STATUS_BUILD_FAILED
                        row["report"] = build.brief()
                        return row
                    candidate = self._call_repair(content, build.brief(), build)
                    stop = no_progress_reason(content, candidate)
                    if stop:
                        row["status"] = STATUS_BUILD_FAILED
                        row["report"] = f"{build.brief()}\n(stopped: {stop})"
                        return row
                    content, row["compile_rounds"] = candidate, row["compile_rounds"] + 1
                    continue
                row["built"] = True

            if not runner.available():
                row["status"] = STATUS_UNVERIFIED
                row["report"] = runner.unavailable_reason()
                break
            if gold_file is None or not gold_file.ok:
                row["status"] = STATUS_NO_GOLD
                row["report"] = (
                    gold_file.error
                    if gold_file is not None and gold_file.error
                    else f"No gold result for {query.id}."
                )
                break

            outcome = runner.run(query, level=level.name)
            if not outcome.ok:
                if row["correctness_rounds"] >= max_correctness:
                    row["status"] = STATUS_RUN_FAILED
                    row["report"] = outcome.brief()
                    return row
                candidate = self._call_repair(content, outcome.brief(), None)
                stop = no_progress_reason(content, candidate)
                if stop:
                    row["status"] = STATUS_RUN_FAILED
                    row["report"] = f"{outcome.brief()}\n(stopped: {stop})"
                    return row
                content, row["correctness_rounds"] = candidate, row["correctness_rounds"] + 1
                continue
            row["ran"] = True

            comparison = self._compare(gold_file.path, outcome.output)
            row["report"] = comparison.brief()
            if comparison.matched:
                row["status"] = STATUS_MATCHED
                row["matched"] = True
                row["runtime_s"] = round(outcome.runtime_s, 6)
                break
            row["mismatch"] = comparison.model_dump(mode="json")
            if row["correctness_rounds"] >= max_correctness:
                row["status"] = STATUS_MISMATCH
                return row
            candidate = self._call_repair(content, comparison.brief(), None)
            stop = no_progress_reason(content, candidate)
            if stop:
                row["status"] = STATUS_MISMATCH
                row["report"] = f"{comparison.brief()}\n(stopped: {stop})"
                return row
            content, row["correctness_rounds"] = candidate, row["correctness_rounds"] + 1

        if row["status"] == STATUS_MATCHED and not row["cache_hit"]:
            # Only a verified implementation is cached, so a re-run retries a
            # broken one instead of returning it from disk forever.
            self.cache.put(
                key,
                {"source": content, "predictor": row["predictor"], "notes": row["notes"]},
                meta={"stage": self.name, "query": query.id, "model": cfg.model.name},
            )
        return row

    # --- model calls ------------------------------------------------------

    def _call_model(self, payload: dict[str, str]) -> dict[str, Any]:
        return invoke(
            _signature_class(),
            payload,
            outputs=("source_code", "notes"),
            cfg=self.cfg,
            writer=self.writer,
            stage=self.name,
            require_api_key=self.ctx.require_api_key,
            workspace=self._tool_workspace(),
            allow_writes=True,
            allow_build=True,
        )

    def _call_repair(self, current: str, report: str, result: Optional[CompileResult]) -> str:
        instruction = self.registry.render(
            FIX_PROMPT_ID,
            variables={
                "compiler": self.cfg.compile.compiler,
                "cpp_standard": self.cfg.compile.cpp_standard,
                "command": " ".join(result.command) if result and result.command else "(n/a)",
                "diagnostics": report,
            },
        )
        value = invoke(
            repair_signature(),
            {"instruction": instruction.text, "report": report, "current_code": current},
            outputs=("fixed_code", "explanation"),
            cfg=self.cfg,
            writer=self.writer,
            stage=self.name,
            require_api_key=self.ctx.require_api_key,
            workspace=self._tool_workspace(),
            allow_writes=True,
            allow_build=True,
        )
        return extract_code(value["fixed_code"])

    # --- configuration helpers -------------------------------------------

    def _param(self, name: str, default: Any) -> Any:
        value = self.cfg.params.get(name)
        return default if value is None else value

    def _get_levels(self) -> list[LevelConfig]:
        """Return all active levels, supporting generation of multiple levels sequentially.

        Returns:
            All active levels to be generated. The stage will iterate through each one.
        """
        levels = self.cfg.resolved_active_levels()
        return levels

    def _source_path(self, query: Query, level: LevelConfig) -> str:
        """Where a query's generated source is written.

        Nested under the level's name whenever more than one level is active,
        so two levels generating the same query id do not overwrite each
        other's source file (and so a later level's leftover file from an
        earlier level can't make ``_setup_build_environment`` believe a full
        dispatch build is already wired up for a level it never generated).
        """
        directory = str(self._param("source_dir", "src/queries")).strip("/")
        if len(self._get_levels()) > 1:
            directory = f"{directory}/{level.name}" if directory else level.name
        return f"{directory}/{query.slug}.cpp" if directory else f"{query.slug}.cpp"

    def _include_line(self, header_path: Path, workspace: Any) -> str:
        return f'#include "{workspace.rel(header_path)}"'

    def _entry_signature(self, level: LevelConfig) -> str:
        override = self.cfg.params.get("entry_signature")
        if override:
            return str(override)
        params = self.cfg.params
        db_type = params.get("database_type_name", "Database")
        db_param = params.get("database_param_name", "db")
        prefix = params.get("query_namespace_prefix", "queries::")
        function = params.get("query_function_name", "run")
        return (
            f"void {prefix}{function}(const {level.namespace}::{db_type}& {db_param}, "
            f"std::ostream& out)"
        )

    def _header_rule(self) -> str:
        """The output-format sentence handed to the generator.

        Derived from ``header_mode`` rather than stated separately so the
        instruction and the comparison cannot disagree — an engine told to print
        a header while the comparison drops one from the other side would fail
        every query on a phantom row-count mismatch.
        """
        if self._header_mode() in ("actual", "both"):
            return "Print a header row naming the columns, matching the reference output exactly."
        return (
            "Do not print a header row; the reference output's header row is dropped "
            "before comparison."
        )

    def _header_mode(self) -> str:
        return str(self._param("header_mode", "gold"))

    def _float_tolerance(self) -> float:
        try:
            return float(self._param("float_tolerance", 1e-6))
        except (TypeError, ValueError):
            return 1e-6

    def _max_correctness_rounds(self) -> int:
        try:
            return max(0, int(self._param("max_correctness_rounds", 3)))
        except (TypeError, ValueError):
            return 3

    def _should_build(self, workspace: Any) -> bool:
        """Whether to build the whole project after a file compiles.

        ``"auto"`` builds only when ``_generate_build_entrypoint`` actually
        produced a ``main.cpp`` for this run (single active level, and a
        dataset directory configured) - checking for that instead of an
        existing ``CMakeLists.txt``, since ``_sync_cmake_project`` now
        (re)writes ``CMakeLists.txt`` on demand right before the build rather
        than once ahead of time. A plain source directory without an entry
        point does not fail every query on a configuration error that has
        nothing to do with the generated code.
        """
        setting = self._param("build_project", "auto")
        if isinstance(setting, str) and setting.lower() == "auto":
            return workspace.safe_path(MAIN_REL_PATH).exists()
        return bool(setting)

    def _gold(self, queries: list[Query]) -> GoldSet:
        provider = GoldProvider(self.cfg.gold, timeout_s=self.cfg.compile.timeout_s)
        try:
            return provider.ensure(queries)
        except Exception as exc:
            # Gold being unavailable must not lose the codegen work: every query
            # is reported as no_gold instead, and the stage says why.
            result = GoldSet(mode=self.cfg.gold.mode)
            from agent.stages.gold import GoldFile

            for query in queries:
                result.files[query.id] = GoldFile(
                    query_id=query.id,
                    path=Path(str(self.cfg.gold.dir or "."))
                    / f"{query.slug}{self.cfg.gold.extension}",
                    error=f"{type(exc).__name__}: {exc}",
                )
            return result

    def _runner(self) -> QueryRunner:
        cfg = self.cfg
        return QueryRunner(
            template=cfg.params.get("run_command"),
            project_root=cfg.gen_project_root or cfg.base_dir,
            output_dir=cfg.out_dir or (cfg.artifacts_dir / "query_output"),
            build_dir=cfg.compile.build_dir,
            dataset_dir=cfg.gold.dataset_dir,
            sf=str(cfg.params.get("sf", "")),
            trace_flag=str(cfg.params.get("trace_flag", "")),
            runtime_pattern=cfg.params.get("runtime_pattern"),
            timeout_s=cfg.compile.timeout_s,
        )

    def _compare(self, gold_path: Path, output: str) -> Comparison:
        expected = load_table(gold_path, delimiter=str(self._param("delimiter", ",")))
        actual = parse_table(output, delimiter=str(self._param("delimiter", ",")), source="engine")
        return compare_tables(
            expected,
            actual,
            float_tolerance=self._float_tolerance(),
            header_mode=self._header_mode(),
            sort_rows=bool(self._param("sort_rows", False)),
        )

    def _tool_workspace(self) -> Any:
        if not self.cfg.params.get("rlm_tools"):
            return None
        return self.ctx.workspace_for(self.cfg)

    def _ingestion_signature(self, level: LevelConfig) -> str:
        """The ingestion entry point's exact signature. Must match hppgen's.

        See ``HppGenStage._ingestion_signature`` (``agent/stages/hppgen.py``)
        for why this is dictated rather than left to either model to invent,
        and why the two stages must be configured identically if overridden.
        """
        override = self.cfg.params.get("ingestion_signature")
        if override:
            return str(override)
        db_type = self.cfg.params.get("database_type_name", "Database")
        function = self.cfg.params.get("ingestion_function_name", "build_database")
        return f"{level.namespace}::{db_type} {function}()"

    def _dataset_description(self, dataset_dir: Path) -> str:
        return (
            f"Dataset directory: {dataset_dir}\n"
            "One Parquet file per table, named '<table>.parquet' (e.g. customer.parquet, "
            "orders.parquet, region.parquet), matching the table names used in the header."
        )

    def _dispatch_header(self, level: LevelConfig, header_include: str) -> str:
        """The stable half of query dispatch: just the function-pointer contract.

        Deterministic and independent of which queries exist yet (unlike the
        dispatch *table*, ``query_dispatch.cpp``, which ``_sync_cmake_project``
        regenerates once queries exist), so it can be written once per level
        before the per-query loop runs, and ``main.cpp`` can be generated and
        verified against it immediately.
        """
        db_type = self.cfg.params.get("database_type_name", "Database")
        return (
            "#pragma once\n\n"
            f"{header_include}\n"
            "#include <string>\n"
            "#include <ostream>\n\n"
            f"typedef void (*QueryFunc)(const {level.namespace}::{db_type}&, std::ostream&);\n"
            "QueryFunc get_query_func(const std::string& query_id);\n"
        )

    def _generate_and_verify_file(
        self,
        workspace: Any,
        level: LevelConfig,
        rel_path: str,
        kind: str,
        signature_cls: Any,
        output_field: str,
        payload: dict[str, str],
        prompt_fingerprint: str,
        extra_flags: Optional[Sequence[str]] = None,
    ) -> bool:
        """Generate one file, verified through the same fix_loop hppgen uses.

        Shared by loader/main.cpp generation. Query source generation stays
        separate (see ``_process_query``'s own docstring): it has two
        independent budgets fix_loop cannot express, which the loader and
        main.cpp - each with a single verifier, a syntax-only compile - do not.
        Only a verified result is cached, exactly as hppgen only caches a
        header that compiled.
        """
        cfg = self.cfg
        key = self.cache.make_key(
            {**payload, "level": level.name, "kind": kind},
            prompt_fingerprint=prompt_fingerprint,
            model_signature=cfg.model.signature(),
            kind="stage",
        )

        cached = self.cache.get(key)
        if cached is not None and isinstance(cached.value, dict):
            content = str(cached.value.get("source", ""))
            workspace.write_file(rel_path, content)
            result = workspace.compile_file(rel_path, syntax_only=True, extra_flags=extra_flags)
            return bool(result.ok or result.compiler_missing)

        first = invoke(
            signature_cls,
            payload,
            outputs=(output_field, "notes"),
            cfg=cfg,
            writer=self.writer,
            stage=self.name,
            require_api_key=self.ctx.require_api_key,
            workspace=self._tool_workspace(),
            allow_writes=True,
            allow_build=True,
        )
        last: dict[str, Optional[CompileResult]] = {"result": None}

        def apply(content: str) -> None:
            workspace.write_file(rel_path, content)

        def verify() -> tuple[bool, str]:
            result = workspace.compile_file(rel_path, syntax_only=True, extra_flags=extra_flags)
            last["result"] = result
            return compile_verdict(result)

        def repair(current: str, report: str) -> str:
            return self._call_repair(current, report, last["result"])

        outcome = fix_loop(
            content=extract_code(first[output_field]),
            apply=apply,
            verify=verify,
            repair=repair,
            max_rounds=cfg.compile.max_fix_rounds,
        )
        result = last["result"]
        verified = outcome.ok and not (result is not None and result.compiler_missing)
        if verified:
            self.cache.put(
                key,
                {"source": outcome.content, "predictor": first["predictor"], "notes": first["notes"]},
                meta={"stage": self.name, "level": level.name, "model": cfg.model.name, "kind": kind},
            )
        return verified

    def _generate_build_entrypoint(
        self, workspace: Any, level: LevelConfig, header_path: Path, header_text: str
    ) -> bool:
        """Phase A: LLM-generate the loader and ``main.cpp`` for this level.

        Both are new LLM calls, verified and repaired the same way a header
        is (``fix_loop``, cache only what verified) rather than templated in
        Python, so the model gets compiler feedback on the loader's use of
        the Arrow/Parquet API and on main.cpp's argv handling, and can improve
        against it instead of it being taken on faith. Skips (not critical -
        queries still compile individually via their own run_command) when no
        dataset directory is configured, since the loader would have nothing
        to read.
        """
        dataset_dir = self.cfg.gold.dataset_dir
        if dataset_dir is None:
            return False

        cfg = self.cfg
        entry_signature = self._ingestion_signature(level)
        header_include = self._include_line(header_path, workspace)

        loader_task = self.registry.render_any(
            LOADER_PROMPT_ID,
            inline=cfg.params.get("loader_task"),
            entry_signature=entry_signature,
        )
        loader_payload = {
            "task": loader_task.text,
            "storage_header": header_text,
            "header_include": header_include,
            "entry_signature": entry_signature,
            "dataset_description": self._dataset_description(dataset_dir),
            "cpp_standard": cfg.compile.cpp_standard,
        }
        loader_ok = self._generate_and_verify_file(
            workspace,
            level,
            LOADER_REL_PATH,
            "loader",
            _loader_signature_class(),
            "loader_code",
            loader_payload,
            loader_task.fingerprint,
            extra_flags=arrow_pkgconfig_flags(),
        )
        if not loader_ok:
            return False

        workspace.write_file(DISPATCH_HEADER_REL_PATH, self._dispatch_header(level, header_include))

        main_task = self.registry.render_any(
            MAIN_PROMPT_ID,
            inline=cfg.params.get("main_task"),
            entry_signature=entry_signature,
        )
        main_payload = {
            "task": main_task.text,
            "storage_header_include": header_include,
            "dispatch_header": self._dispatch_header(level, header_include),
            "entry_signature": entry_signature,
            "run_command": str(cfg.params.get("run_command") or ""),
            "cpp_standard": cfg.compile.cpp_standard,
        }
        return self._generate_and_verify_file(
            workspace,
            level,
            MAIN_REL_PATH,
            "main",
            _main_signature_class(),
            "main_code",
            main_payload,
            main_task.fingerprint,
        )

    def _sync_cmake_project(self, workspace: Any, level: LevelConfig) -> bool:
        """Phase B: regenerate CMakeLists.txt, wrapped query copies and the dispatch table.

        Pure Python, no LLM call, so it is cheap enough to call before every
        real build attempt (see ``_process_query``) instead of once ahead of
        time: it always reflects whichever query files currently exist on
        disk, rather than a stale snapshot from before this run's queries
        were (re)written. Returns False (no-op) if no query files exist yet.
        """
        cmake_dir = Path(self.cfg.compile.cmake_dir or workspace.cmake_dir)
        queries_dir = cmake_dir / "src" / "queries"
        query_files = sorted(queries_dir.glob("q*.cpp"))
        if not query_files:
            return False

        wrapped_sources = "\n  ".join(f"q{i}_wrapped.cpp" for i in range(1, len(query_files) + 1))
        cmake_content = f"""cmake_minimum_required(VERSION 3.15)
project(QueryEngine)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Arrow CONFIG REQUIRED)
find_package(Parquet CONFIG REQUIRED)

# Main executable with query dispatch
add_executable(engine
  ${{CMAKE_CURRENT_SOURCE_DIR}}/{MAIN_REL_PATH}
  ${{CMAKE_CURRENT_SOURCE_DIR}}/{LOADER_REL_PATH}
  ${{CMAKE_CURRENT_SOURCE_DIR}}/query_dispatch.cpp
  {wrapped_sources}
)

target_include_directories(engine PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}})
target_link_libraries(engine PRIVATE Arrow::arrow_shared Parquet::parquet_shared)
"""
        (cmake_dir / "CMakeLists.txt").write_text(cmake_content)

        for i, qfile in enumerate(query_files, 1):
            content = qfile.read_text()
            wrapped = content.replace("namespace queries {", f"namespace q{i}_namespace {{")
            (cmake_dir / f"q{i}_wrapped.cpp").write_text(wrapped)

        db_type = self.cfg.params.get("database_type_name", "Database")
        forward_decls = "\n".join(
            f"namespace q{i}_namespace {{ void run(const {level.namespace}::{db_type}& db, "
            f"std::ostream& out); }}"
            for i in range(1, len(query_files) + 1)
        )
        dispatch_cases = "\n  ".join(
            f'if (query_id == "q{i}" || query_id == "{i}") return q{i}_namespace::run;'
            for i in range(1, len(query_files) + 1)
        )
        dispatch_content = f'''#include "{DISPATCH_HEADER_REL_PATH}"

{forward_decls}

QueryFunc get_query_func(const std::string& query_id) {{
  {dispatch_cases}
  return nullptr;
}}
'''
        (cmake_dir / "query_dispatch.cpp").write_text(dispatch_content)
        return True

    def _fail(self, error: str, started: float) -> StageResult:
        return self.make_result(
            status="failed", error=error, duration_s=time.perf_counter() - started
        )


def _tally(report: Mapping[str, Mapping[str, Any]]) -> dict[str, int]:
    """Count queries per terminal status."""
    counts: dict[str, int] = {}
    for row in report.values():
        status = str(row.get("status", "unknown"))
        counts[status] = counts.get(status, 0) + 1
    return counts
